### ISSUE TITLE
Example template generates different output than shown

### ISSUE THREAD

**Issue by karlp** [Edinburgh-Genome-Foundry/blabel#3]
Hi,

I've created a template and css as per the basic example here: https://edinburgh-genome-foundry.github.io/blabel/ and ran the python demo script from the same page, but I get different output:
![Screenshot from 2020-09-02 14-11-42](https://user-images.githubusercontent.com/127907/91994553-3e6b9700-ed26-11ea-8835-4e2c5f885ec3.png)

Running the examples from the _repository_ work, and the difference is the font-family for the label, I believe it's failing to fall back correctly?

Could the website at least be updated to match the repository?

**Comment by veghp** [comment]
Thanks for raising this issue.

The problem is that the fallback font is wider, therefore the text does not fit on the label and is moved on to the next line. This can be confirmed by setting larger `width` or `height` in the css.
The **solution** is to use a narrower font, less template text, or decrease `font-size` in the css.

I'll modify the template html so that it will not be an issue.
