### ISSUE TITLE
Issues printing labels with multiprocessing

### ISSUE THREAD

**Issue by bryand23** [Edinburgh-Genome-Foundry/blabel#7]
I have a flask application that takes a POST request and then processes some tasks asynchronously - one of these tasks is making and printing a label.

Most of the time it works fine, but occasionally I'll get the error message below when the LabelWriter.write_labels() method is called.

```
worker = Process(target=async_tasks, daemon=True, args=(data,))
worker.start()
```

^ This code is called, with the start method set to spawn. This is on macOS 10.15.7, Python 3.7.9.

async_tasks calls several functions, but it consistently errors out on the write_labels method. Restarting apache causes it to work again, but once it starts giving the error, it will persist until apache is restarted.

```
label_writer = LabelWriter("labels/item_template.html",
                                   default_stylesheets=("labels/style.css",))
records = [
            {'label_text': text, 'url': url}
        ]
print('Writing labels')
label_writer.write_labels(records, target='labels/qrcode_and_label.pdf', base_url='.')

```
```
App 66301 output: The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
App 66301 output: Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
```

This is happening despite the fact that I'm not using fork as the start method - so presumably something in the write_labels method is forking?

**Comment by veghp** [comment]
Thank you for reporting this. Not sure that I can help solving this problem, or that the problem is in blabel. It should have been mentioned in the description that all EGF packages were developed on Ubuntu, and have not been tested on other OSs. A search for your error message returned [this](https://github.com/rq/django-rq/issues/375) and [this](https://github.com/pyinstaller/pyinstaller/issues/3027) among others, so the problem seems to be macOS related. As mentioned in [one of the replies](https://github.com/rq/django-rq/issues/375#issuecomment-579027286):

> fork() has always been unsafe on Mac
> spawn* functions should be instead

[Another comment](https://github.com/pyinstaller/pyinstaller/issues/3027#issuecomment-346329715) suggests 

> searching OSX-related mailinglists and forum about how to solve this. While this might be triggered by you application running via the bootloader, the basic principle (or restriction) is not related to PyInstaller

I'll include a notice in the readme about the OS, in a future update.

**Comment by veghp** [comment]
Does [this](https://stackoverflow.com/questions/30669659/multiproccesing-and-error-the-process-has-forked-and-you-cannot-use-this-corefou) and [this](https://stackoverflow.com/questions/64174552/what-does-the-process-has-forked-and-you-cannot-use-this-corefoundation-functio) SO answers solve your problem?

**Comment by bryand23** [comment]
Thanks for the reply!

I thought I had narrowed it down to blabel since this was the step where it always got hung up, but in doing some more debugging I discovered it was actually failing when blabel called weasyprint  - so I opened an issue over there and I think it's sorted now.
